[package]
name = "GuessAWord"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
tokio = { version = "1.43.0", features = ["full"]}
tokio-macros = "2.5.0"
tokio-util = {  version = "0.7.13", features = ["codec"] }
futures = "0.3.31"